backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Date"
        name: "date"
        widget: "datetime"

      - label: "Description"
        name: "description"
        widget: "text"
        required: false

      - label: "Featured Image"
        name: "image"
        widget: "image"
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown"
